<?php

    // include the HTMLGraph class
    require "../class.htmlgraph.php";
    
    
    
    // watch as the width is specified as percent!
    $gr = new HTMLGraph("60%", "350", "Test graph");
    
    

    // now create a BarPlot object (this is the canvas for bars)
    $plot = new HTMLGraph_BarPlot();
    
    // set the colors of all bars added to this plot to red
    $plot->bars->color = "red";

    // the easiest way to add some values to a BarPlot object
    $values = array(70, 1112, 1052, 345);
    
    // add some labels too
    $labels = array("p1_1", "p1_2", "p1_3", "p1_4");

    // add the values the plot
    $plot->add($values, $labels);

    // now create a second BarPlot object
    $plot2 = new HTMLGraph_BarPlot();

    // set the colors of all bars added to this plot to green
    $plot2->bars->color = "green";

    // add some values to the BarPlot object
    $values2 = array(56, 345, 2391, 678);
    
    // add some labels too
    $labels2 = array("p2_1", "p2_2", "p2_3", "p2_4");

    // add the values the plot
    $plot2->add($values2, $labels2);

    // create a BarPlotGroup object
    $group = new HTMLGraph_BarPlotGroup();
    
    // add the plots to the group
    $group->add($plot);
    $group->add($plot2);
    
    // add the group to the graph
    $gr->add($group);

    // add a footnote to the graph
    $gr->footnote->caption = "generated by Zebra Framework PHP HTMLGraph Class 1.0 BETA";
    
    // output the graph
    $gr->render();

?>
