<?php

    // include the HTMLGraph class
    require "../class.htmlgraph.php";
    
    // create a new graph of 300 pixels width and 350 pixels in height and with a title
    $gr = new HTMLGraph("300", "350", "Test graph");
    
    // if you want to override the settings from the template related to title
    $gr->title->style = "text-decoration:underline";
    
    // now create a BarPlot object (this is the canvas for bars)
    $plot = new HTMLGraph_BarPlot();
    
    // the easiest way to add some values to a BarPlot object
    $values = array(70, 1112, 1052, 345);
    
    // set some labels for the bars
    $labels = array("label 1", "label 2", "label 3", "label 4");
    
    // also set custom colors for the first, second and last bar
    // the third bar will be drawn with the color set by the template
    $colors = array("red", "green", "", "blue");

    // add the values and the colors to the plot
    $plot->add($values, $labels, $colors);
    
    // you can also add a bar using the following method
    $plot->add("500", "a bar added in a different way");
    
    // add the plot to the graph
    $gr->add($plot);

    // add a footnote to the graph
    $gr->footnote->caption = "generated by Zebra Framework PHP HTMLGraph Class 1.0 BETA";
    
    // output the graph
    $gr->render();

?>
